#!/bin/sh -e
# Automatically added by dh_installdocs
if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/`booker' -a -d /usr/share/doc/`booker' ]; then
		ln -sf ../share/doc/`booker' /usr/doc/`booker'
	fi
fi
# End automatically added section
# Automatically added by dh_installmenu
if test -x /usr/bin/update-menus ; then update-menus ; fi
# End automatically added section
